// Style reminder: faithful Movion source recreation — original English copy, Montserrat/Inter typography, white header, red #ee1d38, photographic banners, Elementor-like reveal motion.
import { useEffect, useState } from "react";
import { Link, Route, Switch, useLocation } from "wouter";
import { ArrowRight, ChevronDown, Facebook, Instagram, Linkedin, Mail, MapPin, Menu, MoveRight, Phone, X, Twitter, Truck, PackageOpen, Building2, ShieldCheck, Clock3, Star, Check, Plus } from "lucide-react";

const RED = "#ee1d38";
const HERO = "/manus-storage/delivery-team-checking-manifest-with-clients-at-ho-2026-01-08-06-25-55-utc_cfca2b1f.webp";
const ABOUT = "/manus-storage/movers-unloading-boxes-at-residential-home-2026-01-08-06-32-28-utc_7840eba8.webp";
const SERVICE = "/manus-storage/young-company-workers-packing-for-office-move-2026-03-23-23-01-19-utc_80c470e4.webp";
const PACKING = "/manus-storage/parcel-packing-post-office-worker-taping-box-at-w-2026-04-23-16-09-21-utc_43afe373.webp";
const TEAM = ["/manus-storage/Team-1_620d524a.webp", "/manus-storage/Team-2_f06d4ce1.webp", "/manus-storage/Team-3_10e326f4.webp", "/manus-storage/Team-4_d8d4c2f4.webp", "/manus-storage/Team-5_e8d53440.webp"];
const LOGO = "/manus-storage/Movion-Logo-Teks-Black_f03688e2.png";
const WHITE_LOGO = "/manus-storage/Movion-Logo-Teks-White_11f5aa94.png";

function Brand({ light = false }: { light?: boolean }) { return <Link href="/" className={`brand ${light ? "brand-light" : ""}`}><img src={light ? WHITE_LOGO : LOGO} alt="Movion" /></Link>; }

function Header() {
  const [open, setOpen] = useState(false); const [pagesOpen, setPagesOpen] = useState(false); const [location] = useLocation();
  const links = [["Home", "/"], ["About", "/about"], ["Services", "/services"]];
  return <header className="site-header"><Brand /><nav className="desktop-nav">{links.map(([label, href]) => <Link key={label} href={href} className={location === href ? "active" : ""}>{label}</Link>)}<div className="nav-dropdown" onMouseEnter={() => setPagesOpen(true)} onMouseLeave={() => setPagesOpen(false)}><button className={location.startsWith("/team") || location.startsWith("/pricing") || location.startsWith("/faq") || location.startsWith("/blog") ? "active" : ""}>Pages <ChevronDown size={13} /></button>{pagesOpen && <div className="dropdown-menu"><Link href="/team">Team</Link><Link href="/pricing">Pricing</Link><Link href="/faq">Faq</Link><Link href="/blog">Blog</Link></div>}</div><Link href="/contact" className={location === "/contact" ? "active" : ""}>Contact</Link></nav><Link href="/contact" className="pill pill-red header-cta">Get Started <span><ArrowRight size={15} /></span></Link><button className="menu-button" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X /> : <Menu />}</button>{open && <div className="mobile-nav">{[...links, ["Team", "/team"], ["Pricing", "/pricing"], ["Faq", "/faq"], ["Blog", "/blog"], ["Contact", "/contact"]].map(([label, href]) => <Link key={label} href={href} onClick={() => setOpen(false)}>{label}</Link>)}<Link href="/contact" className="pill pill-red" onClick={() => setOpen(false)}>Get Started <ArrowRight size={15} /></Link></div>}</header>;
}

function Footer() { return <footer className="footer"><div className="newsletter"><div><div className="eyebrow light">STAY IN THE LOOP</div><h2>Get Moving Tips And<br />Latest Updates</h2></div><form onSubmit={e => e.preventDefault()}><input type="email" placeholder="Add email" aria-label="Email" /><button className="pill pill-red" type="submit">Subscribe <ArrowRight size={15} /></button></form></div><div className="footer-main"><div className="footer-brand"><Brand light /><p>Lorem ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p><div className="socials"><a href="#" aria-label="Facebook"><Facebook size={16} /></a><a href="#" aria-label="X"><Twitter size={16} /></a><a href="#" aria-label="LinkedIn"><Linkedin size={16} /></a><a href="#" aria-label="Instagram"><Instagram size={16} /></a></div></div><div><h4>Quick Link</h4><Link href="/">Home</Link><Link href="/about">About</Link><Link href="/services">Services</Link><Link href="/team">Project</Link></div><div><h4>Support</h4><a href="#">Help Center</a><Link href="/contact">Contact</Link><Link href="/blog">Blog</Link><Link href="/faq">Faq</Link></div><div><h4>Contact</h4><a href="tel:+12345678900">+1 (234) 567-8900</a><a href="mailto:support@movion.com">support@movion.com</a><span>35 Mosma St, Austin, TX</span><span>Mon – Sat: 08:00 – 18:00</span></div></div><div className="footer-bottom"><span>2026 Copyright © Sparklethings</span><span><a href="#">Privacy Policy</a><a href="#">Terms & Services</a></span></div></footer>; }

function PageBanner({ title, image = true }: { title: string; image?: boolean }) { return <section className={`page-banner ${image ? "page-banner-image" : ""}`} style={image ? { backgroundImage: `linear-gradient(#1118,#1118), url(${SERVICE})` } : undefined}><div><h1>{title}</h1><p><Link href="/">Home</Link><span>»</span>{title}</p></div></section>; }
function Stats() { return <div className="stats reveal">{[["2,306 +", "SUCCESSFUL MOVES"], ["1,500 +", "HAPPY CLIENTS"], ["100 +", "SERVICE AREAS"], ["20 +", "YEARS EXPERIENCE"]].map(([num, label]) => <div className="stat" key={label}><strong>{num}</strong><span>{label}</span></div>)}</div>; }
function ServiceCard({ icon, title, text, image }: { icon: React.ReactNode; title: string; text: string; image: string }) { return <article className="service-card"><div className="icon-box">{icon}</div><h3>{title}</h3><p>{text}</p><div className="card-image" style={{ backgroundImage: `url(${image})` }}></div><Link className="card-arrow" href="/contact"><ArrowRight size={16} /></Link></article>; }

function Home() { return <><Header /><main><section className="hero" style={{ backgroundImage: `linear-gradient(90deg, #101010c9 0%, #1010105c 56%, #10101025 100%), url(${HERO})` }}><div className="hero-copy"><div className="eyebrow light">SMART MOVING SOLUTIONS</div><h1>Fast Secure Moving<br />For Every Journey</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.</p><Link href="/contact" className="pill pill-white">Get Free Quote <span><ArrowRight size={15} /></span></Link></div><Stats /></section><section className="intro section-pad reveal"><div className="split-heading"><div className="eyebrow">WHY CHOOSE US</div><h2>Moving made simple.<br /><em>Confidence</em> at every turn.</h2></div><div className="intro-copy"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.</p><Link href="/about" className="text-link">More About Us <MoveRight size={18} /></Link></div></section><section className="feature-grid reveal"><div className="feature-image" style={{ backgroundImage: `url(${ABOUT})` }}></div><div className="feature-panel"><div className="eyebrow">WHAT WE DO</div><h2>A smoother way to move forward.</h2><div className="feature-list"><div><span className="icon-box"><ShieldCheck size={22} /></span><div><h3>Safe And Reliable</h3><p>Every item is handled with patience, precision, and respect.</p></div></div><div><span className="icon-box"><Clock3 size={22} /></span><div><h3>Professional Service</h3><p>Thoughtful planning keeps your day moving without the stress.</p></div></div></div><Link href="/services" className="pill pill-red">Explore Services <ArrowRight size={15} /></Link></div></section><section className="services-preview section-pad reveal"><div className="section-top"><div><div className="eyebrow">OUR SERVICES</div><h2>Reliable moving services<br />for every need</h2></div><Link href="/services" className="text-link">View All Services <MoveRight size={18} /></Link></div><div className="service-cards"><ServiceCard icon={<Truck />} title="Home Moving" text="A calm, careful move from the first room to the last." image={ABOUT} /><ServiceCard icon={<Building2 />} title="Office Moving" text="Keep your team focused while we handle the heavy lifting." image={SERVICE} /><ServiceCard icon={<PackageOpen />} title="Packing Service" text="Smart packing that protects what matters most to you." image={PACKING} /></div></section></main><Footer /></>; }

function About() { return <><Header /><PageBanner title="About" /><main><section className="about-story section-pad reveal"><div className="eyebrow">ABOUT US</div><h2>Your Reliable Partner Delivering Excellence In Every Move With Professional Service Always You Can Trust</h2><div className="about-layout"><div className="about-image" style={{ backgroundImage: `url(${ABOUT})` }}></div><div className="about-copy"><div className="vision-card"><div className="round-icon">◉</div><div><h3>Vision</h3><p>Lorem ipsum dolor sit amet consectetur adipiscing elit, ac nullam aliquam egestas curabitur.</p></div></div><div className="vision-card"><div className="round-icon">⚑</div><div><h3>Mission</h3><p>Lorem ipsum dolor sit amet consectetur adipiscing elit, ac nullam aliquam egestas curabitur.</p></div></div><p className="body-copy">Lorem ipsum dolor sit amet consectetur adipiscing elit nisl sagittis leo, nullam fermentum torquent vitae hendrerit eros interdum commodo faucibus aptent.</p><Link href="/contact" className="pill pill-red">More About Us <ArrowRight size={15} /></Link></div></div></section></main><Footer /></>; }
function Services() { return <><Header /><PageBanner title="Services" /><main><section className="services-page section-pad reveal"><div className="center-heading"><div className="eyebrow">OUR SERVICES</div><h2>Reliable Moving Services<br />For Every Need</h2></div><div className="service-cards service-cards-large"><ServiceCard icon={<Truck />} title="Home Moving" text="Lorem ipsum dolor sit amet consectetur adipiscing, elit viverra lacus justo tempus." image={ABOUT} /><ServiceCard icon={<Building2 />} title="Office Moving" text="Lorem ipsum dolor sit amet consectetur adipiscing, elit viverra lacus justo tempus." image={SERVICE} /><ServiceCard icon={<PackageOpen />} title="Packing Service" text="Lorem ipsum dolor sit amet consectetur adipiscing, elit viverra lacus justo tempus." image={PACKING} /></div></section></main><Footer /></>; }
function Team() { const people = ["Michael Carter", "Emily Johnson", "Daniel Foster", "Sophia Williams", "Ryan Mitchell"]; return <><Header /><PageBanner title="Team" /><main><section className="team-page section-pad reveal"><div className="center-heading"><div className="eyebrow">OUR TEAM</div><h2>Meet Our Professional<br />Moving Team</h2></div><div className="team-grid">{people.map((name, i) => <article className="team-card" key={name}><div className="team-photo" style={{ backgroundImage: `url(${TEAM[i]})` }}></div><h3>{name}</h3><p>Moving Specialist</p></article>)}</div></section><section className="why-section section-pad reveal"><div className="eyebrow">WHY CHOOSE US</div><h2>Why Choose Movion<br />For Moving Services</h2><div className="why-grid">{[[<ShieldCheck />, "Safe And Reliable Moving Process"], [<Star />, "Trusted By Customers"], [<Truck />, "Professional Team"], [<Check />, "Affordable Pricing"]].map(([icon, text]) => <div key={String(text)}><span className="icon-box">{icon}</span><h3>{text}</h3></div>)}</div></section></main><Footer /></>; }
function Pricing() { const plans: Array<[string, string, string[]]> = [["Starter Move", "$49", ["2 Movers", "2 Hours Moving", "Basic Protection"]], ["Standard Plan", "$99", ["3 Movers", "4 Hours Moving", "Full Protection"]], ["Premium Plan", "$149", ["4 Movers", "8 Hours Moving", "Premium Protection"]]]; return <><Header /><PageBanner title="Pricing" /><main><section className="pricing-page section-pad reveal"><div className="center-heading"><div className="eyebrow">PRICING</div><h2>Flexible Moving Plans<br />For Every Budget</h2></div><div className="pricing-grid">{plans.map(([name, price, items], i) => <article className={`price-card ${i === 1 ? "featured" : ""}`} key={name}><h3>{name}</h3><div className="price">{price}<small>/move</small></div>{items.map(item => <p key={item}><Check size={15} />{item}</p>)}<Link href="/contact" className={`pill ${i === 1 ? "pill-red" : "pill-outline"}`}>Get Started <ArrowRight size={15} /></Link></article>)}</div></section><section className="steps-section section-pad reveal"><div className="eyebrow">HOW IT WORKS</div><h2>Simple Steps For Smooth<br />Moving Experience</h2><div className="steps-grid">{[["01", "Request Quote"], ["02", "Plan Move"], ["03", "We Move"], ["04", "Safe Delivery"]].map(([n, t]) => <div key={n}><span>{n}</span><h3>{t}</h3></div>)}</div></section></main><Footer /></>; }
function Faq() { const [active, setActive] = useState(0); const questions = ["How far in advance should I book my move?", "Do you provide packing services?", "Are my belongings insured during the move?", "Can you move large or fragile items?"]; return <><Header /><PageBanner title="Faq" /><main><section className="faq-page section-pad reveal"><div className="center-heading"><div className="eyebrow">GENERAL QUESTIONS</div><h2>Frequently Asked<br />Questions</h2></div><div className="faq-list">{questions.map((q, i) => <div className={`faq-item ${active === i ? "open" : ""}`} key={q}><button onClick={() => setActive(active === i ? -1 : i)}><span>{q}</span>{active === i ? <X size={18} /> : <Plus size={18} />}</button>{active === i && <p>We recommend booking as early as possible so our team can plan every detail of your move. Our specialists will guide you through the process and answer any questions.</p>}</div>)}</div></section><section className="faq-page section-pad reveal"><div className="center-heading"><div className="eyebrow">PACKING SERVICES</div><h2>Everything You Need<br />For A Smooth Move</h2></div></section></main><Footer /></>; }
function Blog() { const posts = [["How To Pack Your Home Like A Pro", "Moving tips that make the first step feel simple.", ABOUT], ["Moving Day Checklist: What To Remember", "A practical guide for a calm and organized move.", HERO], ["How To Choose The Right Moving Company", "The details that matter when planning your next move.", SERVICE]]; return <><Header /><PageBanner title="Blog" /><main><section className="blog-page section-pad reveal"><div className="center-heading"><div className="eyebrow">BLOG</div><h2>Latest Tips And<br />Moving Insights Guide</h2></div><div className="blog-grid">{posts.map(([title, text, image]) => <article className="blog-card" key={title}><div className="blog-image" style={{ backgroundImage: `url(${image})` }}></div><div className="eyebrow">MOVING TIPS</div><h3>{title}</h3><p>{text}</p><Link href="/contact" className="text-link">Read More <MoveRight size={18} /></Link></article>)}</div></section></main><Footer /></>; }
function Contact() { const [sent, setSent] = useState(false); return <><Header /><PageBanner title="Contact" /><main><section className="contact-page section-pad reveal"><div className="contact-copy"><div className="eyebrow">CONTACT US</div><h2>Get In Touch With<br />Movion Team</h2><p>Lorem ipsum dolor sit amet consectetur, adipiscing elit pulvinar nisi, phasellus taciti sed euismod.</p><div className="contact-details"><div><span className="icon-box"><Phone size={20} /></span><div><h4>Phone</h4><a href="tel:+12345678900">+1 (234) 567-8900</a></div></div><div><span className="icon-box"><Mail size={20} /></span><div><h4>Email</h4><a href="mailto:support@movion.com">support@movion.com</a></div></div><div><span className="icon-box"><MapPin size={20} /></span><div><h4>Address</h4><span>35 Mosma St, Austin, TX</span></div></div></div></div><form className="contact-form" onSubmit={e => { e.preventDefault(); setSent(true); }}><div className="form-grid"><label>NAME<input required placeholder="Enter Name" /></label><label>PHONE<input placeholder="Enter Phone" /></label><label>EMAIL ADDRESS<input required type="email" placeholder="Enter Email" /></label><label>SUBJECT<input placeholder="Write Subject" /></label></div><label>MESSAGE<textarea required placeholder="Write Message" rows={7}></textarea></label><button className="pill pill-red" type="submit">{sent ? "Message Sent" : "Send Message"} <ArrowRight size={15} /></button></form></section></main><Footer /></>; }
function NotFound() { return <><Header /><PageBanner title="404" image={false} /><main><section className="not-found section-pad"><div className="eyebrow">404</div><h2>Page Not Found</h2><Link href="/" className="pill pill-red">Back To Home <ArrowRight size={15} /></Link></section></main><Footer /></>; }
function App() { useEffect(() => { const nodes = document.querySelectorAll<HTMLElement>(".reveal"); const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); } }), { threshold: 0.12, rootMargin: "0px 0px -8% 0px" }); nodes.forEach(node => observer.observe(node)); return () => observer.disconnect(); }, []); return <Switch><Route path="/" component={Home} /><Route path="/about" component={About} /><Route path="/services" component={Services} /><Route path="/team" component={Team} /><Route path="/pricing" component={Pricing} /><Route path="/faq" component={Faq} /><Route path="/blog" component={Blog} /><Route path="/contact" component={Contact} /><Route path="/404" component={NotFound} /><Route component={NotFound} /></Switch>; }
export default App;
