// Style reminder: faithful Movion reproduction — warm white surfaces, charcoal editorial type, Movion red #ee1d38, edge-to-edge photography, compact pill CTAs.
import { useEffect, useState } from "react";
import { Link, Route, Switch, useLocation } from "wouter";
import { ArrowRight, ChevronDown, Facebook, Instagram, Linkedin, Mail, MapPin, Menu, MoveRight, Phone, X, Twitter, Truck, PackageOpen, Building2, ShieldCheck, Clock3 } from "lucide-react";

const RED = "#ee1d38";
const HERO = "/manus-storage/movion-hero_73fec165.jpg";
const ABOUT = "/manus-storage/movion-about_06158e88.jpg";
const SERVICE = "/manus-storage/movion-service_ce4abee0.jpg";
const MARK = "/manus-storage/movion-mark_69f2ccc4.png";

function Brand({ light = false }: { light?: boolean }) {
  return <Link href="/" className={`brand ${light ? "brand-light" : ""}`}><img src={MARK} alt="" /><span>Movion</span></Link>;
}

function Header() {
  const [open, setOpen] = useState(false);
  const [location] = useLocation();
  const links = [["Home", "/"], ["About", "/about"], ["Services", "/services"], ["Pages", "#"], ["Contact", "/contact"]];
  return <header className="site-header">
    <Brand />
    <nav className="desktop-nav">{links.map(([label, href]) => <Link key={label} href={href} className={location === href ? "active" : ""}>{label}{label === "Pages" && <ChevronDown size={14} />}</Link>)}</nav>
    <Link href="/contact" className="pill pill-red header-cta">Get Started <span><ArrowRight size={15} /></span></Link>
    <button className="menu-button" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X /> : <Menu />}</button>
    {open && <div className="mobile-nav">{links.map(([label, href]) => <Link key={label} href={href} onClick={() => setOpen(false)}>{label}</Link>)}<Link href="/contact" className="pill pill-red">Get Started <ArrowRight size={15} /></Link></div>}
  </header>;
}

function Footer() {
  return <footer className="footer">
    <div className="newsletter"><div><div className="eyebrow light">STAY IN THE LOOP</div><h2>Get Moving Tips And<br />Latest Updates</h2></div><form onSubmit={e => e.preventDefault()}><input type="email" placeholder="Add email" aria-label="Email" /><button className="pill pill-red" type="submit">Subscribe <ArrowRight size={15} /></button></form></div>
    <div className="footer-main"><div className="footer-brand"><Brand light /><p>Reliable moving solutions for homes, offices, and every journey in between.</p><div className="socials"><a href="#" aria-label="Facebook"><Facebook size={16} /></a><a href="#" aria-label="X"><Twitter size={16} /></a><a href="#" aria-label="LinkedIn"><Linkedin size={16} /></a><a href="#" aria-label="Instagram"><Instagram size={16} /></a></div></div><div><h4>Quick Link</h4><Link href="/">Home</Link><Link href="/about">About</Link><Link href="/services">Services</Link><a href="#">Project</a></div><div><h4>Support</h4><a href="#">Help Center</a><Link href="/contact">Contact</Link><a href="#">Blog</a><a href="#">Faq</a></div><div><h4>Contact</h4><a href="tel:+12345678900">+1 (234) 567-8900</a><a href="mailto:support@movion.com">support@movion.com</a><span>35 Mosma St, Austin, TX</span><span>Mon – Sat: 08:00 – 18:00</span></div></div>
    <div className="footer-bottom"><span>2026 Copyright © Sparklethings</span><span><a href="#">Privacy Policy</a><a href="#">Terms & Services</a></span></div>
  </footer>;
}

function PageBanner({ title, image = false }: { title: string; image?: boolean }) { return <section className={`page-banner ${image ? "page-banner-image" : ""}`} style={image ? { backgroundImage: `linear-gradient(#1118,#1118), url(${SERVICE})` } : undefined}><div><h1>{title}</h1><p><Link href="/">Home</Link><span>»</span>{title}</p></div></section>; }
function Stats() { return <div className="stats reveal">{[["2,306+", "Successful Moves"], ["1,500+", "Happy Clients"], ["100+", "Service Areas"], ["20+", "Years Experience"]].map(([num, label]) => <div className="stat" key={label}><strong>{num}</strong><span>{label}</span></div>)}</div>; }

function Home() { return <><Header /><main>
  <section className="hero" style={{ backgroundImage: `linear-gradient(90deg, #101010c9 0%, #1010105c 56%, #10101025 100%), url(${HERO})` }}><div className="hero-copy"><div className="eyebrow light">SMART MOVING SOLUTIONS</div><h1>Fast Secure Moving<br />For Every Journey</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.</p><Link href="/contact" className="pill pill-white">Get Free Quote <span><ArrowRight size={15} /></span></Link></div><Stats /></section>
  <section className="intro section-pad reveal"><div className="split-heading"><div className="eyebrow">WHY CHOOSE US</div><h2>Moving made simple.<br /><em>Confidence</em> at every turn.</h2></div><div className="intro-copy"><p>From the first box to the final room, our experienced team brings clarity, care, and a steady hand to every move.</p><Link href="/about" className="text-link">More About Us <MoveRight size={18} /></Link></div></section>
  <section className="feature-grid reveal"><div className="feature-image" style={{ backgroundImage: `url(${ABOUT})` }}></div><div className="feature-panel"><div className="eyebrow">WHAT WE DO</div><h2>A smoother way to move forward.</h2><div className="feature-list"><div><span className="icon-box"><ShieldCheck size={22} /></span><div><h3>Care you can count on</h3><p>Every item is handled with patience, precision, and respect.</p></div></div><div><span className="icon-box"><Clock3 size={22} /></span><div><h3>On time, every time</h3><p>Thoughtful planning keeps your day moving without the stress.</p></div></div></div><Link href="/services" className="pill pill-red">Explore Services <ArrowRight size={15} /></Link></div></section>
  <section className="services-preview section-pad reveal"><div className="section-top"><div><div className="eyebrow">OUR SERVICES</div><h2>Reliable moving services<br />for every need</h2></div><Link href="/services" className="text-link">View All Services <MoveRight size={18} /></Link></div><div className="service-cards"><ServiceCard icon={<Truck />} title="Home Moving" text="A calm, careful move from the first room to the last." image={ABOUT} /><ServiceCard icon={<Building2 />} title="Office Moving" text="Keep your team focused while we handle the heavy lifting." image={SERVICE} /><ServiceCard icon={<PackageOpen />} title="Packing Service" text="Smart packing that protects what matters most to you." image={HERO} /></div></section>
</main><Footer /></>; }
function ServiceCard({ icon, title, text, image }: { icon: React.ReactNode; title: string; text: string; image: string }) { return <article className="service-card"><div className="icon-box">{icon}</div><h3>{title}</h3><p>{text}</p><div className="card-image" style={{ backgroundImage: `url(${image})` }}></div></article>; }

function About() { return <><Header /><PageBanner title="About" /><main><section className="about-story section-pad reveal"><div className="eyebrow">ABOUT US</div><h2>Your Reliable Partner Delivering Excellence In Every Move With Professional Service Always You Can Trust</h2><div className="about-layout"><div className="about-image" style={{ backgroundImage: `url(${ABOUT})` }}></div><div className="about-copy"><div className="vision-card"><div className="round-icon">◉</div><div><h3>Vision</h3><p>Lorem ipsum dolor sit amet consectetur adipiscing elit, ac nullam aliquam egestas curabitur.</p></div></div><div className="vision-card"><div className="round-icon">⚑</div><div><h3>Mission</h3><p>Lorem ipsum dolor sit amet consectetur adipiscing elit, ac nullam aliquam egestas curabitur.</p></div></div><p className="body-copy">Lorem ipsum dolor sit amet consectetur adipiscing elit nisl sagittis leo, nullam fermentum torquent vitae hendrerit eros interdum commodo faucibus aptent, ligula arcu donec integer praesent montes vel habitasse aliquet.</p><div className="socials dark"><a href="#"><Facebook size={16} /></a><a href="#"><Twitter size={16} /></a><a href="#"><Linkedin size={16} /></a></div><Link href="/contact" className="pill pill-red">More About Us <ArrowRight size={15} /></Link></div></div></section></main><Footer /></>; }
function Services() { return <><Header /><PageBanner title="Services" image /><main><section className="services-page section-pad reveal"><div className="center-heading"><div className="eyebrow">OUR SERVICES</div><h2>Reliable Moving Services<br />For Every Need</h2></div><div className="service-cards service-cards-large"><ServiceCard icon={<Truck />} title="Home Moving" text="Lorem ipsum dolor sit amet consectetur adipiscing, elit viverra lacus justo tempus." image={ABOUT} /><ServiceCard icon={<Building2 />} title="Office Moving" text="Lorem ipsum dolor sit amet consectetur adipiscing, elit viverra lacus justo tempus." image={SERVICE} /><ServiceCard icon={<PackageOpen />} title="Packing Service" text="Lorem ipsum dolor sit amet consectetur adipiscing, elit viverra lacus justo tempus." image={HERO} /></div></section></main><Footer /></>; }
function Contact() { const [sent, setSent] = useState(false); return <><Header /><PageBanner title="Contact" image /><main><section className="contact-page section-pad reveal"><div className="contact-copy"><div className="eyebrow">CONTACT US</div><h2>Get In Touch With<br />Movion Team</h2><p>Lorem ipsum dolor sit amet consectetur, adipiscing elit pulvinar nisi, phasellus taciti sed euismod.</p><div className="contact-details"><div><span className="icon-box"><Phone size={20} /></span><div><h4>Phone</h4><a href="tel:+12345678900">+1 (234) 567-8900</a></div></div><div><span className="icon-box"><Mail size={20} /></span><div><h4>Email</h4><a href="mailto:support@movion.com">support@movion.com</a></div></div><div><span className="icon-box"><MapPin size={20} /></span><div><h4>Address</h4><span>35 Mosma St, Austin, TX</span></div></div></div></div><form className="contact-form" onSubmit={e => { e.preventDefault(); setSent(true); }}><div className="form-grid"><label>NAME<input required placeholder="Enter Name" /></label><label>PHONE<input placeholder="Enter Phone" /></label><label>EMAIL ADDRESS<input required type="email" placeholder="Enter Email" /></label><label>SUBJECT<input placeholder="Write Subject" /></label></div><label>MESSAGE<textarea required placeholder="Write Message" rows={7}></textarea></label><button className="pill pill-red" type="submit">{sent ? "Message Sent" : "Send Message"} <ArrowRight size={15} /></button></form></section></main><Footer /></>; }
function App() { useEffect(() => { const nodes = document.querySelectorAll<HTMLElement>(".reveal"); const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); } }), { threshold: 0.12, rootMargin: "0px 0px -8% 0px" }); nodes.forEach(node => observer.observe(node)); return () => observer.disconnect(); }, []); return <Switch><Route path="/" component={Home} /><Route path="/about" component={About} /><Route path="/services" component={Services} /><Route path="/contact" component={Contact} /><Route component={Home} /></Switch>; }
export default App;
